# Generated by Django 5.1.15 on 2026-08-08 15:24

import apps.renders.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('export_settings', '0001_initial'),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenderJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('settings_snapshot', models.JSONField(help_text='Rendering-relevant ExportSettings fields captured at creation time.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('rendering', 'Rendering'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('stage', models.CharField(blank=True, default='', help_text="Coarse current step, e.g. 'encoding'.", max_length=32)),
                ('output_file', models.FileField(blank=True, null=True, upload_to=apps.renders.models.render_output_path)),
                ('error_message', models.TextField(blank=True, default='')),
                ('export_settings', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='render_jobs', to='export_settings.exportsettings')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='render_jobs', to='videos.uploadedvideo')),
            ],
            options={
                'db_table': 'renders_render_job',
                'ordering': ['-created_at'],
            },
        ),
    ]
