# Generated by Django 5.1.15 on 2026-08-07 20:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capability', models.CharField(choices=[('stt', 'Speech-to-text'), ('llm', 'Large language model'), ('image_gen', 'Image generation')], max_length=32)),
                ('provider_key', models.CharField(help_text="Registry key, e.g. 'ollama' — must match domain.ai.registry.", max_length=64)),
                ('display_name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='Lower runs first when multiple are active.')),
                ('extra_config', models.JSONField(blank=True, default=dict, help_text='Non-secret config only — no API keys.')),
            ],
            options={
                'db_table': 'ai_providers_config',
                'ordering': ['capability', 'priority'],
                'constraints': [models.UniqueConstraint(fields=('capability', 'provider_key'), name='unique_provider_per_capability')],
            },
        ),
    ]
