# Generated by Django 5.1.15 on 2026-08-07 20:07

import apps.videos.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'videos_project',
            },
        ),
        migrations.CreateModel(
            name='UploadedVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=apps.videos.models.upload_video_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('fps', models.FloatField(blank=True, null=True)),
                ('has_audio', models.BooleanField(blank=True, null=True)),
                ('video_codec', models.CharField(blank=True, default='', max_length=64)),
                ('audio_codec', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('extracting_metadata', 'Extracting metadata'), ('transcribing_and_detecting_scenes', 'Transcribing & detecting scenes'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=40)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('pipeline_steps', models.JSONField(blank=True, default=dict, help_text="Per-step status, e.g. {'transcript': 'running'}.")),
                ('error_message', models.TextField(blank=True, default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='videos.project')),
            ],
            options={
                'db_table': 'videos_uploaded_video',
            },
        ),
    ]
