# Generated by Django 5.1.15 on 2026-08-07 20:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(max_length=16)),
                ('language_confidence', models.FloatField(blank=True, null=True)),
                ('full_text', models.TextField()),
                ('provider', models.CharField(max_length=64)),
                ('model_name', models.CharField(max_length=64)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='videos.uploadedvideo')),
            ],
            options={
                'db_table': 'transcripts_transcript',
            },
        ),
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('index', models.PositiveIntegerField()),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('text', models.TextField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('speaker_label', models.CharField(blank=True, max_length=64, null=True)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='transcripts.transcript')),
            ],
            options={
                'db_table': 'transcripts_segment',
                'ordering': ['index'],
                'constraints': [models.UniqueConstraint(fields=('transcript', 'index'), name='unique_segment_index_per_transcript')],
            },
        ),
    ]
