# Generated by Django 5.1.15 on 2026-08-07 20:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary', models.TextField()),
                ('suggested_title', models.CharField(max_length=255)),
                ('suggested_description', models.TextField()),
                ('suggested_hashtags', models.JSONField(blank=True, default=list)),
                ('llm_provider', models.CharField(max_length=64)),
                ('llm_model', models.CharField(max_length=128)),
                ('raw_response', models.JSONField(blank=True, default=dict, help_text='Raw provider response, for audit/debugging.')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result', to='videos.uploadedvideo')),
            ],
            options={
                'db_table': 'highlights_analysis_result',
            },
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank', models.PositiveIntegerField()),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('rationale', models.TextField()),
                ('score', models.FloatField(blank=True, null=True)),
                ('suggested_clip_title', models.CharField(blank=True, max_length=255, null=True)),
                ('analysis_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='highlights.analysisresult')),
            ],
            options={
                'db_table': 'highlights_highlight',
                'ordering': ['rank'],
            },
        ),
    ]
