# Generated by Django 5.1.15 on 2026-08-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("highlights", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="highlight",
            name="emoji",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="highlight",
            name="transition",
            field=models.CharField(
                blank=True,
                help_text="AI-suggested per-clip transition ('cut' or 'fade'); refines, does not override, ExportSettings.transition_style. See domain/rendering/renderer.py.",
                max_length=8,
                null=True,
            ),
        ),
    ]
