# Generated by Django 5.1.15 on 2026-08-08 18:11

import apps.highlights.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("highlights", "0002_highlight_emoji_highlight_transition"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrollAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("query", models.CharField(max_length=255)),
                ("start_time", models.FloatField()),
                ("end_time", models.FloatField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=apps.highlights.models.upload_broll_path
                    ),
                ),
                ("source_provider", models.CharField(blank=True, default="", max_length=32)),
                ("source_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "analysis_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broll_assets",
                        to="highlights.analysisresult",
                    ),
                ),
            ],
            options={
                "db_table": "highlights_broll_asset",
                "ordering": ["start_time"],
            },
        ),
    ]
