# Generated by Django 5.1.15 on 2026-08-08 14:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('num_highlights', models.PositiveSmallIntegerField(default=3, help_text='How many highlight moments to ask the AI for.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('ai_creativity_level', models.CharField(choices=[('conservative', 'Conservative'), ('balanced', 'Balanced'), ('creative', 'Creative')], default='balanced', max_length=16)),
                ('output_duration_seconds', models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(240)])),
                ('aspect_ratio', models.CharField(choices=[('16:9', '16:9 (Widescreen)'), ('9:16', '9:16 (Vertical / Shorts)'), ('1:1', '1:1 (Square)')], default='9:16', max_length=8)),
                ('caption_style', models.CharField(choices=[('none', 'None'), ('minimal', 'Minimal'), ('bold', 'Bold'), ('karaoke', 'Karaoke (word-by-word)')], default='bold', max_length=16)),
                ('font', models.CharField(choices=[('inter', 'Inter'), ('montserrat', 'Montserrat'), ('anton', 'Anton'), ('roboto', 'Roboto')], default='inter', max_length=16)),
                ('color_theme', models.CharField(choices=[('default', 'Default'), ('vibrant', 'Vibrant'), ('dark', 'Dark'), ('pastel', 'Pastel'), ('monochrome', 'Monochrome')], default='default', max_length=16)),
                ('transition_style', models.CharField(choices=[('none', 'None (hard cuts)'), ('fade', 'Fade'), ('slide', 'Slide'), ('zoom', 'Zoom')], default='fade', max_length=16)),
                ('music_style', models.CharField(choices=[('none', 'None'), ('upbeat', 'Upbeat'), ('chill', 'Chill'), ('dramatic', 'Dramatic'), ('corporate', 'Corporate'), ('cinematic', 'Cinematic')], default='none', max_length=16)),
                ('subtitle_language', models.CharField(default='auto', help_text="ISO 639-1 code, 'auto' to match the detected transcript language, or 'none'.", max_length=8)),
                ('voice_over_style', models.CharField(choices=[('none', 'None'), ('male', 'Male'), ('female', 'Female'), ('neutral', 'Neutral')], default='none', max_length=16)),
                ('broll_type', models.CharField(choices=[('none', 'None'), ('stock_footage', 'Stock footage'), ('ai_generated', 'AI-generated'), ('mixed', 'Mixed')], default='none', max_length=16)),
                ('image_generation_enabled', models.BooleanField(default=False)),
                ('internet_media_search_enabled', models.BooleanField(default=False)),
                ('video_quality', models.CharField(choices=[('720p', '720p'), ('1080p', '1080p'), ('4k', '4K')], default='1080p', max_length=8)),
                ('export_format', models.CharField(choices=[('mp4', 'MP4'), ('mov', 'MOV'), ('webm', 'WebM')], default='mp4', max_length=8)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_settings_list', to='videos.uploadedvideo')),
            ],
            options={
                'verbose_name_plural': 'export settings',
                'db_table': 'export_settings',
                'ordering': ['-created_at'],
            },
        ),
    ]
