# Generated by Django 5.1.15 on 2026-08-08 18:11

import apps.export_settings.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("export_settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportsettings",
            name="export_mode",
            field=models.CharField(
                choices=[
                    ("highlight_reel", "Highlight reel"),
                    ("full_video", "Full video (entire source, polished)"),
                ],
                default="highlight_reel",
                help_text="Highlight reel: a subset of AI-picked moments, fit to output_duration_seconds. Full video: the entire source, in order, with the same captions/B-roll/logo/music polish -- output_duration_seconds and num_highlights are unused in this mode.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="exportsettings",
            name="logo_image",
            field=models.ImageField(
                blank=True,
                help_text="Optional watermark, composited in a fixed corner for the whole render. Presence of a file is what enables it -- no separate toggle.",
                null=True,
                upload_to=apps.export_settings.models.upload_logo_path,
            ),
        ),
        migrations.AlterField(
            model_name="exportsettings",
            name="num_highlights",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="How many highlight moments to ask the AI for.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(30),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="exportsettings",
            name="output_duration_seconds",
            field=models.PositiveSmallIntegerField(
                default=60, validators=[django.core.validators.MinValueValidator(15)]
            ),
        ),
    ]
