# Generated by Django 5.1.15 on 2026-08-08 20:47

import apps.export_settings.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("export_settings", "0002_exportsettings_export_mode_exportsettings_logo_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportsettings",
            name="logo_position",
            field=models.CharField(
                choices=[
                    ("top_left", "Top left"),
                    ("top_right", "Top right"),
                    ("bottom_left", "Bottom left"),
                    ("bottom_right", "Bottom right"),
                ],
                default="bottom_right",
                help_text="Where the logo/watermark sits — always scaled down to a small corner mark, never covering the video.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="exportsettings",
            name="logo_image",
            field=models.ImageField(
                blank=True,
                help_text="Optional watermark, composited in a fixed corner for the whole render. Presence of a file is what enables it -- no separate toggle.",
                max_length=512,
                null=True,
                upload_to=apps.export_settings.models.upload_logo_path,
            ),
        ),
    ]
